### ISSUE TITLE
hexDigit syntax bug?

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/subscript-parser#41]
main/scala/scalaParser/syntax/Basic.scala:
```
def HexDigit = rule( Digit | "a" - "f" | "A" - "Z" )
```
should that not be:
```
def HexDigit = rule( Digit | "a" - "f" | "A" - "F" )
```
?

**Comment by anatoliykmetyuk** [comment]
Yes, indeed. Such errors where the scope of syntax is broader than that in Scala spec are caught on compile-time. But it is good to get rid of this one.

**Comment by AndreVanDelft** [comment]
Ok; will you inform Li about this? Or does that go automatically?

**Comment by anatoliykmetyuk** [comment]
It seems that he already [fixed](https://github.com/lihaoyi/fastparse/blob/master/scalaparse/shared/src/main/scala/scalaparse/syntax/Basic.scala) that. Unfortunately, we're a bit out of date, since our fork sustained big refactoring to allow code injection, and merging the latest version of Fastparse would take time. However, our fork passes all the tests on existing projects, so FTTB we can go with it.
